server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://server-01:8888/eureka/,http://server-02:8888/eureka/
spring:
  redis:
    host: 172.31.204.16
    password:
    pool:
      max-active: 20
      max-idle: 20
      max-wait: 1
      min-idle: 0
    ssl: false
    port: 6379
    timeout: 0
  application:
    name: mars-service
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    locale: zh_CN
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    deserialization: true
    default-property-inclusion: non_null
    generator: true
    mapper: true
    parser: true
    serialization: true
  datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://server-01:3306/mars?useUnicode=true&characterEncoding=utf-8
        username: root
        password: mysql!@#
mybatis:
    typeAliasesPackage: org.xteam.plus.mars.domain
    mapperLocations: classpath*:org/xteam/plus/mars/mapper/*.xml

logging:
  path: /data/log/mars
  level: INFO
  config: classpath:service-logback.xml

mars:
  cache:
    verifycode-life: 2
    verifycode-limit: 30
  test:
    mobileNos: 13701312791,18810863866,13806770481,17319227081,13800000001,13800000002,13800000003,13800000004,13800000005,13800000006,13800000007,13800000008,13800000009,13800000010,13800000011,13800000012
    password: 888888
  employeeCard:
    backGround: backgroud.jpg
    url: http://t.kuai-kaifa.com/index.html?employeeCardNo=
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000