server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
spring:
  redis:
    host: 127.0.0.1
    password:
    pool:
      max-active: 8
      max-idle: 8
      max-wait: 1
      min-idle: 0
    ssl: false
    port: 63790
    timeout: 0
  application:
    name: mars-service
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
  jackson:
    locale: zh_CN
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    deserialization: true
    default-property-inclusion: non_null
    generator: true
    mapper: true
    parser: true
    serialization: true
  datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/mars?useUnicode=true&characterEncoding=utf-8
        username: mars
        password: mars
mybatis:
    typeAliasesPackage: org.xteam.plus.mars.domain
    mapperLocations: classpath*:org/xteam/plus/mars/mapper/*.xml

logging:
  path: d:/logs
  level: debug
  config: classpath:service-logback.xml
