server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
spring:
  application:
    name: mars-service
  redis:
      host: 127.0.0.1
      password:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1
        min-idle: 0
      ssl: false
      port: 6379
      timeout: 0
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    locale: zh_CN
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    deserialization: true
    default-property-inclusion: non_null
    generator: true
    mapper: true
    parser: true
    serialization: true
  datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://113.209.111.211:3306/mars?useUnicode=true&characterEncoding=utf-8
        username: mars
        password: mars
mybatis:
    typeAliasesPackage: org.xteam.plus.mars.domain
    mapperLocations: classpath*:org/xteam/plus/mars/mapper/*.xml

logging:
  path: /var/log/mars
  level: debug
  config: classpath:service-logback.xml

mars:
  cache:
    verifycode-life: 2
    verifycode-limit: 1000
  test:
    mobileNos: 13701312791,18810863866
    password: 888888
  employeeCard:
    backGround: backgroud.jpg
    url: http://113.209.111.211:8080/index.html?employeeCardNo=
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000