server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://server-01:8888/eureka/,http://server-02:8888/eureka/
spring:
  application:
    name: mars-webapp
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
zuul:
  routes:
    mars-webapp:
      path: /webservice/**
      serviceId: mars-service
ribbon:
    ReadTimeout: 30000
    ConnectTimeout: 30000
logging:
  path: /data/log/mars
  level: INFO
  config: classpath:webapp-logback.xml