server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
spring:
  application:
    name: mars-webapp
zuul:
  routes:
    mars-webapp:
      path: /webservice/**
      serviceId: mars-service
logging:
  path: /data/log/mars
  level: debug
  config: classpath:webapp-logback.xml